version: '3.9'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: vectorscaledb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5555:5432"
    volumes:
      - vectorscale_data:/var/lib/postgresql/data

volumes:
  vectorscale_data:
